### ISSUE TITLE
creating and assigning an issue

### ISSUE THREAD

**Issue by LeeKilgore** [thelondonp/thelondonp.github.io#1]
Hi London,
I am creating this "issue" for you to see how the system works on github.  So the issue I am assigning is for you to create and assign an issue to me.  When you do it, you can add a comment to this issue and/or close this issue.  

To create an issue, click on the issues tab at the top of the github project just under your name and project name.  Click the green "new issue" button.  make and issue and click the green "submit new issue"  at the bottom.

Then assign it to me.  If you look around on the page you will see where to to this.

**Comment by thelondonp** [comment]
i'm confused

**Comment by LeeKilgore** [comment]
OK start here:
https://github.com/thelondonp/thelondonp.github.io

then click on the "issues" tab right below the project name to go here:
https://github.com/thelondonp/thelondonp.github.io/issues

then click on the "new issue" button that is green over on the upper right and go here:
https://github.com/thelondonp/thelondonp.github.io/issues/new

make an issue, then over on the right, assign it to me with the "assignee" button.

**Comment by LeeKilgore** [comment]
I think you got it.  I'm closing the first issue.
